spring:
  datasource:
    username: admin
    url: jdbc:h2:file:./db/bookdb
    driverClassName: org.h2.Driver
    password: password

  h2:
    console:
      enabled: 'true'
      path: /db-console
  application:
    name: springstarter

  #JPA => hibernate? ???(SQL?? ??)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #?? dialect ??? ?? ??? ? -> h2dialect ??
    properties:
      hibernate:
        format_sql: 'true' #?? ??
    hibernate:
      ddl-auto: update # @Entity -> create SQL. ??? ?? ? create ??. ? ??? update ? ?? ??.
#      naming: #
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #??? ?? ?? ??? ??? ??.
    show-sql: 'true'

server:
  port: '8081'




#spring.application.name=springstarter
#
#
##tomcat ?? ?? ?? ??
#server.port = 8081
#
##Set the context path to "/web/"
##server.servlet.context-path=/web/
#
## ?????? ?? #driver name, url, username, password ????.   # ?????? ?? ?(??? ?). ??? ????? ??? ?? ???? ??? ???.
## ??? ?. ?? ???? ???? ?? ??? ???? ????, ?? ??? ??? ??? ? ??? ?? ??.HikariCP? ??? ?? ??? ?(Connection Pool) ????????.
#spring.datasource.url=jdbc:h2:file:./db/bookdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## H2 ?????? ??(????)
#spring.h2.console.enabled=true
#spring.h2.console.path=/db-console
#
## ?????? ???
#spring.jpa.hibernate.ddl-auto=update
#
## ??? SQL ?? ?? ?? ??
#spring.jpa.show-sql=true
#
## ??? SQL ??? ?? ?? ???.
#spring.jpa.properties.hibernate.format_sql=true